name: GlobalMute
version: 1.0-SNAPSHOT
main: com.acktardevs.globalmute.Main
author: Acktar
api: ["1.0.0"]

commands:
      globalmute:
          description: Mute the global chat
          permission: globalmute.admin
   
permissions:
      globalmute.bypass:
          description: Bypasses the globalmute
      globalmute.admin:
          default: op
          description: admin commands for globalmute
      
